"""Output format generators for the packed digest.

Supports three formats: Markdown, XML, and Plain Text.
Each takes the same inputs and produces a single string ready
for saving to disk or passing to an LLM.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

from repobrief import __version__
from repobrief.packer.tree import render_directory_tree
from repobrief.scanner.models import ScannedFile
from repobrief.scoring.tokenizer import count_tokens


class OutputFormat(Enum):
    """Supported output formats."""

    MARKDOWN = "markdown"
    XML = "xml"
    PLAIN = "plain"


@dataclass
class PackingMetadata:
    """Metadata about the packing operation, used in the digest header.

    Attributes:
        repo_name: Name of the repository (directory name).
        files_included: Number of files in the digest.
        files_scanned: Total files found by the scanner (before filtering).
        tokens_used: Total tokens in the selected files.
        token_budget: The configured token budget.
    """

    repo_name: str
    files_included: int
    files_scanned: int
    tokens_used: int
    token_budget: int


# -- Language detection for syntax highlighting --------------------------------

EXTENSION_TO_LANGUAGE = {
    ".py": "python",
    ".js": "javascript",
    ".ts": "typescript",
    ".jsx": "jsx",
    ".tsx": "tsx",
    ".java": "java",
    ".kt": "kotlin",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".swift": "swift",
    ".r": "r",
    ".R": "r",
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "zsh",
    ".ps1": "powershell",
    ".sql": "sql",
    ".html": "html",
    ".htm": "html",
    ".css": "css",
    ".scss": "scss",
    ".less": "less",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".xml": "xml",
    ".md": "markdown",
    ".dockerfile": "dockerfile",
    ".tf": "terraform",
    ".lua": "lua",
    ".dart": "dart",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".hs": "haskell",
    ".scala": "scala",
    ".clj": "clojure",
    ".vue": "vue",
    ".svelte": "svelte",
}


def _detect_language(file_path: Path) -> str:
    """Detect the programming language from file extension.

    Returns:
        Language identifier string (for syntax highlighting), or empty string.
    """
    ext = file_path.suffix.lower()
    # Handle special filenames
    name = file_path.name.lower()
    if name == "dockerfile":
        return "dockerfile"
    if name == "makefile":
        return "makefile"
    return EXTENSION_TO_LANGUAGE.get(ext, "")


# -- Format Implementations ----------------------------------------------------


def format_markdown(
    files: list[ScannedFile],
    metadata: PackingMetadata,
) -> str:
    """Format the digest as Markdown.

    Args:
        files: List of selected ScannedFile objects.
        metadata: Packing metadata for the header.

    Returns:
        Complete Markdown digest string.
    """
    lines: list[str] = []

    # Header
    lines.append(f"# Repository: {metadata.repo_name}\n")
    lines.append("## Summary\n")
    lines.append(
        f"- **Files included**: {metadata.files_included} / {metadata.files_scanned} scanned"
    )
    lines.append(f"- **Total tokens**: {metadata.tokens_used:,} / {metadata.token_budget:,} budget")
    lines.append(f"- **Generated by**: RepoBrief v{__version__}\n")

    # Directory tree
    lines.append("## Directory Structure\n")
    lines.append("```")
    tree = render_directory_tree(
        [f.relative_path for f in files],
        root_name=metadata.repo_name,
    )
    lines.append(tree.rstrip())
    lines.append("```\n")

    # Files
    lines.append("## Files\n")
    for file in files:
        lang = _detect_language(file.relative_path)
        rel_path_posix = file.relative_path.as_posix()
        lines.append(f"### `{rel_path_posix}`\n")
        lines.append(f"```{lang}")
        lines.append(file.content.rstrip())
        lines.append("```\n")

    return "\n".join(lines)


def format_xml(
    files: list[ScannedFile],
    metadata: PackingMetadata,
) -> str:
    """Format the digest as XML.

    Args:
        files: List of selected ScannedFile objects.
        metadata: Packing metadata for the header.

    Returns:
        Complete XML digest string.
    """
    lines: list[str] = []
    lines.append('<?xml version="1.0" encoding="UTF-8"?>')
    lines.append(f'<repository name="{xml_escape(metadata.repo_name)}">')

    # Summary
    lines.append("  <summary>")
    lines.append(f"    <files_included>{metadata.files_included}</files_included>")
    lines.append(f"    <files_scanned>{metadata.files_scanned}</files_scanned>")
    lines.append(f"    <total_tokens>{metadata.tokens_used}</total_tokens>")
    lines.append(f"    <token_budget>{metadata.token_budget}</token_budget>")
    lines.append(f"    <generator>RepoBrief v{__version__}</generator>")
    lines.append("  </summary>")

    # Directory tree
    tree = render_directory_tree(
        [f.relative_path for f in files],
        root_name=metadata.repo_name,
    )
    lines.append("  <directory_tree>")
    lines.append(f"    {xml_escape(tree.rstrip())}")
    lines.append("  </directory_tree>")

    # Files
    lines.append("  <files>")
    for file in files:
        rel_path_posix = file.relative_path.as_posix()
        file_tokens = count_tokens(file.content)
        lines.append(
            f'    <file path="{xml_escape(rel_path_posix)}" '
            f'tokens="{file_tokens}" size="{file.size_bytes}">'
        )
        lines.append(f"      <content>{xml_escape(file.content.rstrip())}</content>")
        lines.append("    </file>")
    lines.append("  </files>")

    lines.append("</repository>")
    return "\n".join(lines)


def format_plain(
    files: list[ScannedFile],
    metadata: PackingMetadata,
) -> str:
    """Format the digest as plain text.

    Args:
        files: List of selected ScannedFile objects.
        metadata: Packing metadata for the header.

    Returns:
        Complete plain text digest string.
    """
    sep = "=" * 80
    lines: list[str] = []

    # Header
    lines.append(sep)
    lines.append(f"Repository: {metadata.repo_name}")
    lines.append(f"Files included: {metadata.files_included} / {metadata.files_scanned} scanned")
    lines.append(f"Total tokens: {metadata.tokens_used:,} / {metadata.token_budget:,} budget")
    lines.append(f"Generated by: RepoBrief v{__version__}")
    lines.append(sep)
    lines.append("")

    # Directory tree
    lines.append("DIRECTORY STRUCTURE:")
    tree = render_directory_tree(
        [f.relative_path for f in files],
        root_name=metadata.repo_name,
    )
    lines.append(tree.rstrip())
    lines.append("")

    # Files
    for file in files:
        rel_path_posix = file.relative_path.as_posix()
        lines.append(sep)
        lines.append(f"FILE: {rel_path_posix}")
        lines.append(sep)
        lines.append(file.content.rstrip())
        lines.append("")

    return "\n".join(lines)


# -- Public API ----------------------------------------------------------------


def pack_digest(
    files: list[ScannedFile],
    metadata: PackingMetadata,
    output_format: OutputFormat = OutputFormat.MARKDOWN,
) -> str:
    """Pack selected files into a formatted digest string.

    This is the main public entry point for the packer module.

    Args:
        files: List of selected ScannedFile objects.
        metadata: Packing metadata for the header.
        output_format: Which format to produce.

    Returns:
        The complete formatted digest as a string.

    Raises:
        ValueError: If output_format is not recognized.
    """
    formatters = {
        OutputFormat.MARKDOWN: format_markdown,
        OutputFormat.XML: format_xml,
        OutputFormat.PLAIN: format_plain,
    }

    formatter = formatters.get(output_format)
    if formatter is None:
        raise ValueError(f"Unsupported output format: {output_format}")

    return formatter(files, metadata)
